#ifndef NAVCOIN_CHAINPARAMSSEEDS_H
#define NAVCOIN_CHAINPARAMSSEEDS_H
/**
 * List of fixed seed nodes for the navcoin network
 * AUTOGENERATED by contrib/seeds/generate-seeds.py
 *
 * Each line contains a 16-byte IPv6 address and a port.
 * IPv4 as well as onion addresses are wrapped inside a IPv6 address accordingly.
 */
tatic SeedSpec6 pnSeed6_main[] = {
    {{0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0xff, 0xff, 0xc7, 0xf7, 0x01, 0x54}, 8430},
    {{0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0xff, 0xff, 0x42, 0x2a, 0x7d, 0xbc}, 8430}
};

static SeedSpec6 pnSeed6_test[] = {};

static SeedSpec6 pnSeed6_dev[] = {};

#endif // NAVCOIN_CHAINPARAMSSEEDS_H
